import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'
import Conversation from '../components/Conversation'
import FeaturedStar from '../components/FeaturedStar'
import Logo from '../components/Logo'
import ModelIcon from '../components/Model'
import ModelCard from '../components/ModelCard'
import QouteCard from '../components/QouteCard'
import Smile from '../components/Smile'
import { Heading1, Heading2, Heading3, Paragraph, SmallParagraph } from '../components/Typography'
import HeroImage from "../public/images/hero.png"
import AboutTeam from "../public/images/AboutTeam.png"

const navigation = [
  { name: 'Blog', href: '#', current: true },
  { name: 'Mission', href: '#', current: false },
  { name: 'Contact', href: '#', current: false },
]

const modelCards = [
  {
    name: "inspring-stories",
    title: <span className='text-blue-500'>Inspiring stories</span>,
    subtitle: "Highlight heroes among us who live to show us that’s its possible",
    className: "bg-blue-50"
  },
  {
    name: "active-community",
    title: <span className='text-amber-700'>Active community</span>,
    subtitle: "Highlight heroes among us who live to show us that’s its possible",
    className: "bg-amber-50"
  },
  {
    name: "network",
    title: <span className='text-green-500'>Network of resources</span>,
    subtitle: "Highlight heroes among us who live to show us that’s its possible",
    className: "bg-green-50"
  },
]

function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}

export default function Home() {
  return (
    <div className='max-w-7xl w-full mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='py-6 flex justify-between items-center'>
        <div className='space-x-2 flex items-center'>
          <Logo />
          <span className='text-lg font-bold text-gray-800'>Mission Sustainability</span>
        </div>
        <div className="hidden lg:py-2 lg:flex lg:space-x-8" aria-label="Global">
          {navigation.map((item) => (
            <a
              key={item.name}
              href={item.href}
              className={classNames(
                item.current ? 'bg-gray-100 text-gray-900' : 'text-gray-700 hover:bg-gray-50 hover:text-gray-900',
                'rounded-md py-2 px-3 inline-flex items-center text-sm'
              )}
              aria-current={item.current ? 'page' : undefined}
            >
              {item.name}
            </a>
          ))}
        </div>

      </nav>
      <main className='pb-40'>
        <div className='grid grid-cols-2 gap-16 py-20'>
          <div className='flex flex-col justify-between'>
            <Heading1 className="pr-64 font-poppins">
              Let’s make sustainability a reality
            </Heading1>
            <Paragraph>
              Our mission is to empower individuals, society, and organisations who are interested in living more harmoniously with nature. To begin with, we are amplifying stories of ecoprenuers that inspire our generation to take action.
            </Paragraph>
          </div>
          <Image className='w-full' src={HeroImage} role="presentation" alt='' />
        </div>
        <div className='py-20 mt-40'>
          <div className='flex space-x-2 items-center'>
            <ModelIcon />
            <Heading2>The model</Heading2>
          </div>
          <Paragraph className="mt-6 max-w-3xl">
            To bring change, we need an ecosystem connecting like-minded people and enabling them to make positive changes. Our vision is to enable exchange of information and resources to make it easy for everyone live sustainably.
          </Paragraph>
          <div className="mt-16 mx-auto grid gap-16 lg:grid-cols-3">
            {modelCards.map(({ className, name, title, subtitle }) =>
              <ModelCard
                key={name}
                className={className}
                coverImage={
                  <img className="h-48 w-full object-cover" src="https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1679&amp;q=80" alt="" />
                }
                title={title}
                subtitle={subtitle}
              />)}
          </div>
        </div>
        <div className='py-20 mt-40'>
          <div className='flex space-x-2 items-center py-14'>
            <FeaturedStar />
            <Heading2>Featured story</Heading2>
          </div>
          <div className='grid grid-cols-2 gap-16'>
            <Image className='w-full' src={HeroImage} role="presentation" alt='' />
            <div className='flex flex-col px-6 items-start'>
              <div className='space-y-6 flex-1'>
                <Heading3 className="font-poppins">
                  Converting cow dung into eco-freindly papers - story of Jaipur startup
                </Heading3>
                <Paragraph>
                  Imagine a world where the stationery you buy saves trees and makes our cities cleaner. It prevents polluting water bodies, provides revenue for rural areas, and helps in the welfare of cows. If you dispose of that stationary in pots, it acts as manure blossoming in your surroundings. And this entire process makes you more sensitive to our relationship with nature. Sounds too ideal!? Not with Gaukriti
                </Paragraph>
              </div>
              <Button>Read more</Button>
            </div>
          </div>
        </div>
        <div className='py-20 mt-40 grid grid-cols-2 gap-24'>
          <div className='px-12'>
            <Conversation />
            <Heading2 className="mb-20">Our dialog with the change makers</Heading2>
            <QouteCard />
            <Paragraph className="mt-20">
              In 2019, we started looking for inspiration and learn first-hand how can one take actions to give back to nature instead of just taking from it. Against all the odds in today’s world. We are absolutely honored to get time to have deep discussions with these changemakers in India.
            </Paragraph>
            <Paragraph className="mt-8">
              We look forward to many such insightful meetings!
            </Paragraph>
          </div>
          <div className='space-y-10'>
            <QouteCard />
            <QouteCard />
          </div>
        </div>
        <div className='grid grid-cols-2 gap-16 py-20 mt-40'>
          <div className='flex flex-col justify-between items-start'>
            <div>
              <div className='flex space-x-2 items-center'>
                <Smile />
                <Heading2>Who we are</Heading2>
              </div>
              <Paragraph className="mt-10">
                Just two friends trying to find inspiration and solutions to share it with like-minded people. Many of us do want to reduce our impact on nature but don’t see any feasible way. Thus, ending up with regular lifestyle and mindset.
              </Paragraph>
              <Paragraph className="mt-8">
                One needs motivation and belief that its possible and meangiful to contribute without difficult changes in life. We are trying our bit to enable that.
              </Paragraph>
            </div>
            <button
              type="button"
              className="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900"
            >
              Learn more
            </button>
          </div>
          <div className='relative'>
            <Image className='w-full rounded-xl' src={AboutTeam} role="presentation" alt='' />
            <div className='absolute p-6 bg-green-300 w-1/2 translate-x-1/2 -translate-y-1/2'>Optimistcally looking forward to add many more people in this picture. Two of us can’t do much you know!</div>
          </div>
        </div>

      </main>

      <footer>
      </footer>
    </div>
  )
}
